### ISSUE TITLE
Include LICENSE file

### ISSUE THREAD

**Issue by azenla** [grafnu/bacnet4j#11]
It appears that this repository does not include a COPYING or LICENSE file that displays the license. I work for Radix IoT which maintains bacnet4j at https://github.com/InfiniteAutomation/bacnet4j and just noticed this repository is missing the LICENSE file. It would be fantastic if this could be added in accordance with GPLv3 requirements and recommendations, see https://www.gnu.org/licenses/gpl-faq.en.html here for more details.

Thanks

**Comment by grafnu** [comment]
Kenneth -- finally got around to updating this!  The license.txt file is
there just like your repo.

Cheers,
  Trevor

**Comment by azenla** [comment]
Thanks @grafnu 👍
